### ISSUE TITLE
Does this still work? do you still work on this? will there be more documentation?

### ISSUE THREAD

**Issue by github-userx** [totgezockt/askfmProfileGrabber#1]
Have you tried this under linux as well?

Do you know about this one already? 

https://github.com/LordOfTheSnow/AskFM-Grabber

**Comment by totgezockt** [comment]
Hi,
thanks for eminding me again. I had kind of forgotten about this application. I sat down and updated the complete repository including all code that goes with it.
I have not tried to run it under linux, but I think as long as you are running a desktop environment it should work. If you do try, please go ahead and report your  success/failure :)
Also I did not know of the python version from @LordOfTheSnow, but that should also not be relevant, because I needed a Java application.

And thanks for bringing me back to this ;)

Greetings,
Moritz

**Comment by github-userx** [comment]
Thanks so much for the response Moritz!

Why Did You choose or need it as a Java app?

I am so used nowadays to my simple python scripts :) that archive everything,e.g. instaloader.

I will try to run the java version on Linux soon and report back to You.

I am really into social media archiving, so finding your app / project was awesome.

Kind Regards
